### ISSUE TITLE
release 0.2

### ISSUE THREAD

**Issue by xuwei-k** [dwango/slack-webhook-appender#14]

**Comment by xuwei-k** [comment]
テストコメント

**Comment by xuwei-k** [comment]
テストコメント

**Comment by xuwei-k** [comment]
誰もやらないようなら、(mavenよくわからないので)自分がそのうちsbtに書き換えつつやってしまおうかなぁ

**Comment by piclane** [comment]
僕はお願いしたいです！

**Comment by xuwei-k** [comment]
done

- https://github.com/dwango/slack-webhook-appender/releases/tag/v0.2.0
- https://github.com/dwango/slack-webhook-appender/pull/15
- https://github.com/dwango/slack-webhook-appender/commit/bd90270b3e54afa6c5769d46aea85eba30caf166
