### ISSUE TITLE
Use of Webhook Appender

### ISSUE THREAD

**Issue by Andre601** [dwango/slack-webhook-appender#18]
Hey.

This is more of a simple question, rather than an issue.
It is probably even this kind of question that a google-search may solve, but I still want to ask here.

I want to implement this thing into the logback.xml, to send Webhooks, on any type of error, that could happen.
A friend already helped me on setting something up ([link](https://github.com/Andre601/NekoBot/blob/dev/src/main/resources/logback.xml#L35-L75)).
The question now is, if I can replace the link in `<webhookUrl>` with some sort of function, to get the link (for example getting it from the config.json), since I don't want to publicly show the link on the GitHub and give peoples a way to mess around with it... And I also don't want to always remove the link temporarily only to publish the code and then re-add it.
If there is no such way, then I (sadly) have to search for an alternative since I try to keep such information as private as possible.

**Comment by piclane** [comment]
You can use the parameter of logback.

like this:
foo.java
```
System.setProperty("WEBHOOK_URL", getWebhookUrlFromConfig());
```

logback.xml
```
<webhookUrl>${WEBHOOK_URL}</webhookUrl>
```

**Comment by Andre601** [comment]
Is foo.java just an example-class?
And does it matter, where I make the `System.setProperty`?

**Comment by piclane** [comment]
foo.java is just example.
Please call `System.setProperty` before logback.xml is loaded. I think that it is a proper timing before calling [`LoggerFactory.getLogger (PurrBot.class);`](https://github.com/Andre601/NekoBot/blob/dev/src/main/java/com/andre601/PurrBot/core/PurrBot.java#L71)
If you want to call `System.setProperty` in the `main()` function, I recommend that you use like [this](https://gist.github.com/piclane/8b8abe28f558f00d02246a4247e1ffc2) to lazy loading logback.xml.
Using LazyLoggerFactory.java, loback.xml is loaded when you first write the log.

**Comment by Andre601** [comment]
I honestly don't understand a single thing....

**Comment by piclane** [comment]
ok, update like this:

[PurrBot.java](https://github.com/Andre601/NekoBot/blob/dev/src/main/java/com/andre601/PurrBot/core/PurrBot.java#L71)
```
    private static Logger logger = (Logger) LazyLoggerFactory.getLogger(PurrBot.class);

    public static EventWaiter waiter = new EventWaiter();

    public static void main(String[] args){

        builder = new JDABuilder(AccountType.BOT);

        file.make("config", "./config.json", "/config.json");

        System.setProperty("WEBHOOK_URL", file.getItem("config", "webhookURL"));

        ...
```

**Comment by piclane** [comment]
OMG
LazyLoggerFactory.getLogger do not return ch.qos.logback.classic.Logger object...

update like this
```
    static {
        file.make("config", "./config.json", "/config.json");

        System.setProperty("WEBHOOK_URL", file.getItem("config", "webhookURL"));
    }

    private static Logger logger = (Logger) LoggerFactory.getLogger(PurrBot.class);

    public static EventWaiter waiter = new EventWaiter();

    public static void main(String[] args){

        builder = new JDABuilder(AccountType.BOT);

        ...
```

**Comment by Andre601** [comment]
And that works?
Can't really think about, why it would run like that since I don't know how `static` would actually be activated...
But I'm still a beginner in Java so... 🤷‍♂️

**Comment by piclane** [comment]
Maybe this code works.
try that code copy & paste😃

**Comment by Andre601** [comment]
The solution is imo a bit more simple: Adding `void <something>()` to make it a void and execute it as first option in the main()

**Comment by Andre601** [comment]
I'll look if that will now work and let you know...

**Comment by Andre601** [comment]
Alright, I tested it and... it doesn't work at all. Sorry, but I can't use that and have to remove it from my dependencies.

**Comment by Andre601** [comment]
Since I don't really use that anymore.....
